[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["service_chaining"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "service_chaining"
  org = "choreopmm"
  version = "3.1.1"

