openapi: 3.0.1
info:
  title: /
  version: 3.1.1
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "8090"
paths:
  /employee/{employeeId}:
    get:
      operationId: getEmployeeEmployeeid
      parameters:
      - name: employeeId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        "500":
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    Employee:
      required:
      - department
      - name
      - title
      type: object
      properties:
        name:
          type: string
        title:
          type: string
        department:
          type: string
